version: "3.7"
services:
  db:
    image: mysql
    networks:
      - database
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  api:
    build: ./api
    working_dir: /ivm
    networks:
      - api
    volumes:
      - ./api:/ivm

  nginx:
    image: nginx:1.15
    working_dir: /ivm
    networks:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./api:/api
      - ./ui:/ui
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  database:
  api: